volumes:
  postgres:

services:
  api:
    container_name: looms-pos-api
    build:
      context: .
      dockerfile: Looms.Pos/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '8081:8081'

  postgres:
    image: postgres:14.3-alpine
    container_name: looms-pos-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:cached
    healthcheck:
      test: pg_isready -U user -d default
      interval: 5s
      timeout: 5s
      retries: 5
